GET http://localhost/items


###

POST http://localhost/items
Content-Type: application/json

{
    "id": 4,
    "name": "item 4"
}

###

PUT http://localhost/items/4
Content-Type: application/json

{
    "id": 4,
    "name": "item 4 (updated)"
}

###

DELETE http://localhost/items/3
