GET https://effective-space-palm-tree-9wrj7w5jxqjc76pj-3000.app.github.dev/items


###

POST https://effective-space-palm-tree-9wrj7w5jxqjc76pj-3000.app.github.dev/items
Content-Type: application/json

{
    "id": 4,
    "name": "item 4"
}

###

PUT https://effective-space-palm-tree-9wrj7w5jxqjc76pj-3000.app.github.dev/items/4
Content-Type: application/json

{
    "id": 4,
    "name": "item 4 (updated)"
}

###

DELETE https://effective-space-palm-tree-9wrj7w5jxqjc76pj-3000.app.github.dev/items/3
